package service

import (
	"context"
	"strings"

	cachev1alpha1 "service-cache-operator/pkg/apis/cache/v1alpha1"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	logf "sigs.k8s.io/controller-runtime/pkg/runtime/log"
	"sigs.k8s.io/controller-runtime/pkg/source"
)

var log = logf.Log.WithName("controller_service")

/**
* USER ACTION REQUIRED: This is a scaffold file intended for the user to modify with their own Controller
* business logic.  Delete these comments after modifying this file.*
 */

// Add creates a new Service Controller and adds it to the Manager. The Manager will set fields on the Controller
// and Start it when the Manager is Started.
func Add(mgr manager.Manager) error {
	return add(mgr, newReconciler(mgr))
}

// newReconciler returns a new reconcile.Reconciler
func newReconciler(mgr manager.Manager) reconcile.Reconciler {
	return &ReconcileService{client: mgr.GetClient(), scheme: mgr.GetScheme()}
}

// add adds a new Controller to mgr with r as the reconcile.Reconciler
func add(mgr manager.Manager, r reconcile.Reconciler) error {
	// Create a new controller
	c, err := controller.New("service-controller", mgr, controller.Options{Reconciler: r})
	if err != nil {
		return err
	}

	// Watch for changes to primary resource Service
	err = c.Watch(&source.Kind{Type: &corev1.Service{}}, &handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}

	// Watch for changes to secondary resource Pods and requeue the owner Service
	err = c.Watch(&source.Kind{Type: &cachev1alpha1.ServiceCache{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &corev1.Service{},
	})
	if err != nil {
		return err
	}

	return nil
}

// blank assignment to verify that ReconcileService implements reconcile.Reconciler
var _ reconcile.Reconciler = &ReconcileService{}

// ReconcileService reconciles a Service object
type ReconcileService struct {
	// This client, initialized using mgr.Client() above, is a split client
	// that reads objects from the cache and writes to the apiserver
	client client.Client
	scheme *runtime.Scheme
}

// Reconcile reads that state of the cluster for a Service object and makes changes based on the state read
// and what is in the Service.Spec
// TODO(user): Modify this Reconcile function to implement your Controller logic.  This example creates
// a Pod as an example
// Note:
// The Controller will requeue the Request to be processed again if the returned error is non-nil or
// Result.Requeue is true, otherwise upon completion it will remove the work from the queue.
func (r *ReconcileService) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	reqLogger := log.WithValues("Request.Namespace", request.Namespace, "Request.Name", request.Name)
	reqLogger.Info("Reconciling Service")

	// Fetch the Service instance
	instance := &corev1.Service{}
	err := r.client.Get(context.TODO(), request.NamespacedName, instance)
	if err != nil {
		if errors.IsNotFound(err) {
			// Request object not found, could have been deleted after reconcile request.
			// Owned objects are automatically garbage collected. For additional cleanup logic use finalizers.
			// Return and don't requeue
			return reconcile.Result{}, nil
		}
		// Error reading the object - requeue the request.
		return reconcile.Result{}, err
	}

	if instance.Labels["service-cache.github.io/author"] == "auto-generated" {
		// The service is auto-generated by servicecache-controller, so Return and don't requeue
		return reconcile.Result{}, nil
	}

	// get or create the Service Cache object
	serviceCache, err := r.getOrCreateServiceCache(instance)
	if err != nil {
		return reconcile.Result{}, err
	}

	// TODO: update service cache based on service's configuration
	serviceCache.Spec.CacheableByDefault = (instance.Annotations["service-cache.github.io/default"] == "true")
	urls := instance.Annotations["service-cache.github.io/URLs"]
	urls = strings.TrimSuffix(strings.TrimPrefix(urls, "["), "]")
	serviceCache.Spec.URLs = strings.Split(urls, ",")

	// Set Service instance as the owner and controller
	if err := controllerutil.SetControllerReference(instance, serviceCache, r.scheme); err != nil {
		return reconcile.Result{}, err
	}

	// Service Cache object is up to date now, so don't requeue
	reqLogger.Info("Skip reconcile: ServiceCache is now up to date", "ServiceCache.Namespace", serviceCache.Namespace, "ServiceCache.Name", serviceCache.Name)
	return reconcile.Result{}, nil
}

// getOrCreateServiceCache returns a ServiceCache object
func (r *ReconcileService) getOrCreateServiceCache(svc *corev1.Service) (*cachev1alpha1.ServiceCache, error) {
	logger := log.WithValues("ServiceCache.Namespace", svc.Namespace, "ServiceCache.Name", svc.Name)
	found := &cachev1alpha1.ServiceCache{}
	err := r.client.Get(context.TODO(), types.NamespacedName{Name: svc.Name, Namespace: svc.Namespace}, found)
	if err != nil && errors.IsNotFound(err) {
		found.Name = svc.Name
		found.Namespace = svc.Namespace
		found.Spec.CacheableByDefault = false
		logger.Info("Creating a new ServiceCache", "ServiceCache.Namespace", found.Namespace, "ServiceCache.Name", found.Name)
		err = r.client.Create(context.TODO(), found)
	}
	return found, err
}
